# Generated by Django 4.1.7 on 2023-04-06 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=2500)),
                ('instructions', models.CharField(max_length=2500)),
                ('servings', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('calories_per_serving', models.IntegerField()),
                ('total_protein', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_fat', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
